//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradientFlowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DATA_USER_APPLICATION
    {
        public long ID { get; set; }
        public long USER_ID { get; set; }
        public long ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    }
}
