//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradientFlowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DATA_QUESTIONS
    {
        public long ID { get; set; }
        public string CONTENT { get; set; }
        public bool REPLIED { get; set; }
        public long SUBMITTING_USER_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public long MODIFIED_USERID { get; set; }
    }
}
