//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradientFlowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PARAMS_VALUATIONS
    {
        public long ID { get; set; }
        public string VALUATION_TITLE { get; set; }
        public string VALUATION_DESCRIPTION { get; set; }
        public long VALUATION_TYPE_ID { get; set; }
        public long CREATED_USER_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public long MODIFIED_USERID { get; set; }
    }
}
