//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradientFlowDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GradientFlowDBEntities : DbContext
    {
        public GradientFlowDBEntities()
            : base("name=GradientFlowDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_DATA_ANSWERS> APP_DATA_ANSWERS { get; set; }
        public virtual DbSet<APP_DATA_EVALUATIONS> APP_DATA_EVALUATIONS { get; set; }
        public virtual DbSet<APP_DATA_QUESTIONS> APP_DATA_QUESTIONS { get; set; }
        public virtual DbSet<APP_DATA_USER_APPLICATION> APP_DATA_USER_APPLICATION { get; set; }
        public virtual DbSet<APP_DATA_USER_PERSONAL> APP_DATA_USER_PERSONAL { get; set; }
        public virtual DbSet<APP_DATA_USERS> APP_DATA_USERS { get; set; }
        public virtual DbSet<APP_PARAMS_PROJECTS> APP_PARAMS_PROJECTS { get; set; }
        public virtual DbSet<APP_PARAMS_TABLE_SETTINGS> APP_PARAMS_TABLE_SETTINGS { get; set; }
        public virtual DbSet<APP_PARAMS_TABLES> APP_PARAMS_TABLES { get; set; }
        public virtual DbSet<APP_PARAMS_TOPICS> APP_PARAMS_TOPICS { get; set; }
        public virtual DbSet<APP_PARAMS_VALUATION_TYPES> APP_PARAMS_VALUATION_TYPES { get; set; }
        public virtual DbSet<APP_PARAMS_VALUATIONS> APP_PARAMS_VALUATIONS { get; set; }
        public virtual DbSet<SYS_USER_LOGIN> SYS_USER_LOGIN { get; set; }
    }
}
