USE [GradientFlowDB]
GO

/****** Object:  Table [dbo].[APP_PARAMS_TOPICS]    Script Date: 10/12/2023 16:51:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_PARAMS_TOPICS]') AND type in (N'U'))
DROP TABLE [dbo].[APP_DATA_QUESTIONS]
GO

/****** Object:  Table [dbo].[APP_PARAMS_TOPICS]    Script Date: 10/12/2023 16:51:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_DATA_QUESTIONS](
	[ID] [bigint] NOT NULL,
	[CONTENT] [nvarchar](500) NOT NULL,
	[REPLIED] [BIT] NOT NULL DEFAULT 0,
	[SUBMITTING_USER_ID] [BIGINT] NOT NULL,
	[PROJECT_ID] [bigint] NULL,
	[CREATED_DATE] [datetime] NOT NULL default GETDATE(),
	[MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_USERID] [bigint] NOT NULL

 CONSTRAINT [PK_APP_DATA_QUESTIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


