USE [GradientFlowDB]
GO

/****** Object:  Table [dbo].[APP_PARAMS_TOPICS]    Script Date: 10/12/2023 16:51:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_PARAMS_TOPICS]') AND type in (N'U'))
DROP TABLE [dbo].[APP_PARAMS_VALUATIONS]
GO

/****** Object:  Table [dbo].[APP_PARAMS_TOPICS]    Script Date: 10/12/2023 16:51:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_PARAMS_VALUATIONS](
	[ID] [bigint] NOT NULL,
	[VALUATION_TITLE] [nvarchar] (50) NOT NULL,
	[VALUATION_DESCRIPTION] [nvarchar] (50) NOT NULL,
	[VALUATION_TYPE_ID] [bigint] NOT NULL,
	[CREATED_USER_ID] [BIGINT] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL default GETDATE(),
	[MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_USERID] [bigint] NOT NULL

 CONSTRAINT [PK_APP_PARAMS_VALUATIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


